### ISSUE TITLE
Saving throws (key terms)

### ISSUE THREAD

**Issue by bjornbm** [kensanata/halberdsnhelmets#10]
Page 10:

> **Saving Throw:** Targets of spells are sometimes granted a saving throw in order to avoid negative effects or to reduce damage taken by half. The spell descriptions will explicitly mention any saving throws granted. Saving throws depend on your level. To make it, roll a d20 and add your wisdom bonus. You must get number indicated or higher.

This text addresses only saving against spells, but the class descriptions (page 3+) show saving throws for many categories (to most of which, I understand, the wisdom bonus does not apply).

**Comment by kensanata** [comment]
Hm. Actually it applies nearly always. If the medusa petrifies you, that's magic. Dragon breath is magic. Right now I can only think of poison and deadly natural situations like drowning as counter examples. Perhaps the rules would be easier to apply if we simply granted the bonus without asking whether magic is involved.

**Comment by bjornbm** [comment]
Agree. Explosions and those alien rayguns may also be non-magic. But in most cases I think it is also fair to argue that your wisdom represents how perceptive and/or in tune with the world you are, a kind of sixth sense where your gut feeling allows you to react that split second faster, or whatever is required. Or wisdom as willpower when that is more applicable (drowning?). Poison is perhaps not well justified as constitution seems a more appropriate bonus for poison save-or-die, but special casing that would defeat simplicity.

**Comment by kensanata** [comment]
I usually take a successful save vs. poison when you're hit as successfully evading the poison: the spider jumped on you, and struggled, and now you're a bit more tired (lost some hit points), but with luck (and wisdom, I guess), you managed to jam your shield into the spider's mouth instead of getting bitten (mad your save vs. poison)

**Comment by kensanata** [comment]
Feel free to reopen! :)
