### ISSUE TITLE
Morale or morale score?

### ISSUE THREAD

**Issue by bjornbm** [kensanata/halberdsnhelmets#13]
Use either "morale" or "morale score" consistently in the below.

Page 2:

> **Charisma** determines how well others react to you, how many retainers and pets will follow you (4 + your bonus) and their morale score (7 + your bonus).

Page 8 (table header):

> Category ______ Wage _______ Morale

Page 10:

> If 2d6 _exceed_ the morale score, morale breaks and opponents flee.

Page 11:

> Their morale is determined by the player character: 7 + charisma bonus (4–10). If they roll higher than their morale, these retainers retire.

**Comment by kensanata** [comment]
Morale is better! 69cec93
