### ISSUE TITLE
Ghostscript destroys hyperlinks

### ISSUE THREAD

**Issue by bjornbm** [kensanata/halberdsnhelmets#15]
You are probably aware already that the `gs` post-processing destroys the links/refs, which is a shame. :(

**Comment by kensanata** [comment]
Yeah. I'm thinking we need some changes to the Makefile which reduce the quality of all the images depending on how they are used, and then create the PDF without post-processing. That was simply the easy way out: specially because the referee guide is about 50MB with all the original images in it.

**Comment by kensanata** [comment]
I added the print targets *print* and *online* to the Makefile. These simply change the symbolic link for the graphics to either the original images or very small ones (300px wide, i.e. one inch in print at 300dpi or two to four inch on a monitor, depending on it's pixel density). I think that solves it?

**Comment by kensanata** [comment]
Feel free to reopen.

**Comment by bjornbm** [comment]
Nice! Works for me and I believe the images in the online version look better than before (in my PDF reader. Worth the increase in file size if you ask me. 👍
