### ISSUE TITLE
Confusing numbers

### ISSUE THREAD

**Issue by bjornbm** [kensanata/halberdsnhelmets#16]
Page 11:

> **Retainers:** Unlike mercenaries, retainers are loyal. Their number is limited, however: 4 + charisma bonus (1–7). After disastrous adventures, they’ll need to make a Morale Check. Their morale is determined by the player character: 7 + charisma bonus (4–10). If they roll higher than their morale, these retainers retire.

I think those numbers in parentheses are more confusing than helpful. I think it is clear enough without them. I am pretty sure that if I hadn't listened to that podcast episode where you discuss them before reading this I would have been confused and wondering why they were there and what they meant. If you _really_ want to keep them perhaps rewrite the parens as "(i.e., between 4 and 10)".

**Comment by kensanata** [comment]
Good idea, I'll drop them.

**Comment by kensanata** [comment]
More changes that I had mentioned in the podcast. be9bfed

**Comment by kensanata** [comment]
I'm very happy with the changes I ended up making to the retainer section after all the feedback. Thank you very much!

**Comment by bjornbm** [comment]
I'm glad that you find it valuable and not just annoying nitpicking! I'll review the updated section and open new issues for any comment.

By the way I just read the three posts on retainers at <https://bxblackrazor.blogspot.com/2011/07/bx-charisma-henchmen-part-3_18.html> that I think I found via your blog/wiki. Gave me a bit of a new perspective on the topic.
