### ISSUE TITLE
Smaller charisma bonus for 2d6

### ISSUE THREAD

**Issue by bjornbm** [kensanata/halberdsnhelmets#17]
> **Reaction Bonus:** This bonus is a bit smaller than the charisma bonus because the _reaction_ roll uses 2d6 instead of a d20.

I am nit-picking, but I understand that this reasoning does not apply to the morale check (which also uses 2d6).

Is it worth special casing for the Reaction Roll? Will charisma having greater impact on reaction make play worse? Or will it make charisma more interesting? (Hypothetical questions; you are the one with experience to judge.)

**Comment by kensanata** [comment]
I guess it's simply tradition. On page B7 of the Moldvay book, there's actually a small table:

```
Charisma	Adjustment	Maximum number	Morale of
Score		to Reactions	of retainers	retainers
  3		    -2		      1		     4
 4-5		    -1		      2		     5
 6-8		    -1		      3		     6
 9-12		   None		      4		     7
 etc
```

**Comment by bjornbm** [comment]
OK. Yes, I listened to the podcast episode where you talk about this during a walk today.
