### ISSUE TITLE
Mass combat and NPCs?

### ISSUE THREAD

**Issue by bjornbm** [kensanata/halberdsnhelmets#23]
Ref guide page 9:

> **Player characters can “hide” within a unit**, granting them their charisma bonus for morale checks. When the unit takes damage, the player and non-player characters are the last ones to actually take damage. All these characters attack as usual, with separate attack rolls and separate spell casting actions.

Not sure what you mean with “non-player characters“ here; isn't everyone in the unit (except the PC) an NPC, or do you have another term for the faceless nameless extras? Did you mean "retainers"?

**Comment by kensanata** [comment]
Yeah, retainers.
