### ISSUE TITLE
Control character in Ref-Guide

### ISSUE THREAD

**Issue by bjornbm** [kensanata/halberdsnhelmets#25]
Regarding Github considering `Halberds-and-Helmets-Ref-Guide.ltx` to be a binary file (see #24), so does the unix `file` tool:

    Halberds-and-Helmets-Ref-Guide.ltx: data

Investigating it turns out you have a control character in a comment on line 158. After removing/replacing that character `file` is much happier:

    Halberds-and-Helmets-Ref-Guide.ltx: LaTeX 2e document text, UTF-8 Unicode text

I believe [Github is happier too](https://github.com/bjornbm/halberdsnhelmets/blob/textguide/Halberds-and-Helmets-Ref-Guide.ltx).

**Comment by kensanata** [comment]
Fixed in c068633.
