### ISSUE TITLE
Nitpick: Apostrophe or 'RIGHT SINGLE QUOTATION MARK' (U+2019)?

### ISSUE THREAD

**Issue by bjornbm** [kensanata/halberdsnhelmets#26]
While hunting down the control character in #25 I noticed that sometimes you have used a 'RIGHT SINGLE QUOTATION MARK' (U+2019) as sometimes an apostrophe. As far as I can tell they render identically in the PDF, but for consistency (and searchability) you may want to pick one?

This seems relevant: https://tedclancy.wordpress.com/2015/06/03/which-unicode-character-should-represent-the-english-apostrophe-and-why-the-unicode-committee-is-very-wrong/

**Comment by kensanata** [comment]
Fixedin 951caec. We cannot U+02BC [as recommended](https://tedclancy.wordpress.com/2015/06/03/which-unicode-character-should-represent-the-english-apostrophe-and-why-the-unicode-committee-is-very-wrong/) because we're going to get "not set up for use with LaTeX."

**Comment by bjornbm** [comment]
Seem like the right trade-off for LaTeX and keyboard convenience! (Might not be true for your local keyboard of course.)

**Comment by kensanata** [comment]
I think a long time ago I hoped to get a Markdown version going, basically plain text. Haha.

**Comment by bjornbm** [comment]
I have a RPG system/rules project where I am trying to keep my source in markdown while still being able to use LaTeX goodness. Inspired by https://randomdeterminism.wordpress.com/2012/06/01/how-i-stopped-worring-and-started-using-markdown-like-tex/. The nice thing is of course that the source files are nicer to read than LaTeX.

I also try to make/keep it compatible with github wiki pages (via an alternate set of `gpp` macros) thinking that might be a nice resource when my campaign goes live… not sure it is worth the extra effort though.

You can see my repo at https://bitbucket.org/bjornbm/korthack/src/ if the approach interests you. The text is in Swedish. Let me know if you want explanation of the how it “works”.

However: don't take this as a recommendation! It would be a big effort and you may not be able to get the results you want anyway.
