### ISSUE TITLE
Elementals

### ISSUE THREAD

**Issue by bjornbm** [kensanata/halberdsnhelmets#29]
> _Dimension Door_ (4th circle) allows you to send yourself or another up to 360 ft away in any direction. You do not need to see or know the target area. If the target area is occupied, the spell fails without any adverse effects

I assume that strictly speaking is is a volume and not an area? Perhaps area is the more common nomenclature? Feel free to ignore and close. :)

**Comment by kensanata** [comment]
Haha, you are technically correct but I don't think anybody uses the words "target volume".

**Comment by bjornbm** [comment]
Haha, yes, what I expected :D

**Comment by bjornbm** [comment]
By the way, you have a handful of references to the temple of elemental bickering and its author. Whether or not that should change is for you to decide, but I wanted to mention it so that at least it is an active choice on your behalf rather than just forgotten (in case it was).

**Comment by kensanata** [comment]
Oh, right. 😥

**Comment by kensanata** [comment]
b40117f
