### ISSUE TITLE
Conflagration

### ISSUE THREAD

**Issue by bjornbm** [kensanata/halberdsnhelmets#30]
> _Conflagration_ (3rd circle) weakens the boundaries to the planes of eternal fire anywhere within 180 ft and causes the floors and walls in a circle with a diameter of 40 ft to erupt in flames dealing 1d6 damage per level and **_destroying building any flammable material_**.

Something is not right there at the end.

**Comment by kensanata** [comment]
You are right. I think removing "building" should fix that. b8a0b70
