### ISSUE TITLE
Death & Dismemberment links to wrong page

### ISSUE THREAD

**Issue by bjornbm** [kensanata/halberdsnhelmets#31]
For some reason the link to “death and dismemberment” in the helmet notes on page 7 takes me to page 12 instead of page 13 where the table of _Death & Dismemberment_ is found.

**Comment by kensanata** [comment]
I can confirm it but everything looks correct in the LaTeX source, doesn't it? `key:death` is set and used correctly, as far as I can tell.

**Comment by bjornbm** [comment]
I couldn't see any obvious problem with the source either (otherwise I would have submitted a pull request). Oh, [the joys of LaTeX](https://alexschroeder.ch/wiki/2019-02-15_The_LaTeX_Curse).

**Comment by bjornbm** [comment]
I think `\label` attaches to the latest (nominally) “numbered” item, which in this case would be the `\section` _Combat_ on page 12. Have no good ideas for how to “fix”.

**Comment by kensanata** [comment]
What do you think of 2589078? There's no more space for the chase rule but I also hardly ever use it, so perhaps that's OK.

**Comment by bjornbm** [comment]
I think it is a worthwhile tradeoff.

Separating injury from combat seems to make sense to me.

The chase rule, while interesting, was a little grating to me in that it seemed like one would suddenly be playing Dungeon World. Having mechanical guidance is nice, but maybe the chase rule was too much page space and stylistic dissonance in relation to what it added over making a ruling in the moment. (This is just gut feeling and speculation on my part.)
