### ISSUE TITLE
Skills

### ISSUE THREAD

**Issue by bjornbm** [kensanata/halberdsnhelmets#32]
> The big table of d6:
>
>| Skill |  1d6 |
>|:-----|:----:|
>|Default|1|
>|Kick in doors, **add your strength bonus**| 1–2|

When written like this I would normally assume that the strength bonus is added to the die roll, but in this case then intent must be to add the bonus to the “1–2” range. Should it be made more clear?

Also the table in general doesn't get much explanation. For example that the right column is the required result to succeed. If I hadn't listened to your podcast on skills before reading I would have been a bit puzzled.

**Comment by kensanata** [comment]
Good points. I guess we could change all the numbers to be target numbers, so rolling high is good, and then adding the strength bonus to the roll is the natural thing to do, but everyday language often talks uses "one-in-six chance" and the like, so I'm unsure about the wording. Do you have a suggestion? I think the page has enough whitespace in the sidebar so that we can add a "How to use this table" paragraph before "In most cases..."

**Comment by bjornbm** [comment]
Changing to target numbers would address is, but I sympathise with your objection.

You could do something like the following, but the wider right column will be problematic for the longer items:

| Activity |  Chance of success |
|:-----|-----:|
|Default|1 in 6|
|Kick in doors| (2 + strength bonus) in 6|
|Trigger, evade or disarm traps|2 in 6|

Using the sidebar to document the table sounds reasonable.

**Comment by kensanata** [comment]
What do you think of 7f0e46d?

**Comment by bjornbm** [comment]
I would propose replacing “The big table of d6:” with “Roll a d6: you succeed when you roll the number indicated.” Like so:

```tex
Roll a d6: you succeed when you roll the number indicated.
  \marginnote{For feats of strength, allow the strength
  bonus to improve your chances:
  …
```

I.e., move the one-line instruction to just above the table.

**Comment by bjornbm** [comment]
I feel that perhaps the top of the table could be improved. Do “Skill” and “1d6” really add much value? Would “Default” be better replaced by “Most activities” or something similar?

Actually I think I find “Default” works better without the first row, so I would suggest just dropping the first row of the table (assuming you make the change in my previous comment).

**Comment by kensanata** [comment]
Or we could try "Anything not listed below"

**Comment by kensanata** [comment]
08911d9.

**Comment by bjornbm** [comment]
I like it.
