### ISSUE TITLE
That’s when you get to research new spells.

### ISSUE THREAD

**Issue by bjornbm** [kensanata/halberdsnhelmets#33]
Margin note on page 1. Is this still relevant? Anyway there is a nonexistent key:

    LaTeX Warning: Hyper reference `key:Research' on page 1 undefined on input line

**Comment by kensanata** [comment]
Good point. I removed research, I think.

**Comment by bjornbm** [comment]
Yes, in 8adfcafce706a50904a29feef76188ac13c1e418.

**Comment by kensanata** [comment]
Fixed in 1ffe24d.
