### ISSUE TITLE
Elaborate on Earth blood?

### ISSUE THREAD

**Issue by bjornbm** [kensanata/halberdsnhelmets#37]
This may be considered a blog/wiki article request rather than an HH issue (or both if you prefer). But I am writing here as I am not sure what would otherwise be the most a suitable way to reach you.

In the Monsters section you have several references to Earth blood. They are very evocative but also quite vague. In [My Goblins](https://alexschroeder.ch/wiki/2011-03-14_My_Goblins) you write “my vision of earth blood being responsible for magic” and elsewhere you write about poisoned Earth blood. I would love to learn more about your concept/vision of Earth blood… why it rises to the surface.

There is an [Earthblood product on DTRPG](https://www.drivethrurpg.com/product/58346/Earthblood) (which I have yet to read) with the following blurb, but I really want to hear your vision!

> Far below the surface world lie the veins through which the earth’s own blood flows. Earthblood makes possible life in the Underdark. Its mystic energies sustain many of the strange plants and fungi that grow there in the same way that the sun gives life to all flora of the sunlit world.

Thanks and happy holiday season!

**Comment by kensanata** [comment]
Haha, no problem. Another way of reaching me would be [mail](https://alexschroeder.ch/wiki/Contact), I guess. I did write [a blog post](https://alexschroeder.ch/wiki/2019-12-20_Earth_Blood), now.

**Comment by bjornbm** [comment]
Thanks! Somehow I thought I tried to find contact details to you sometime earlier (when I first started listening to your podcast and looking at Halberds & Helmets) and failed to find an email address. But either I misremember or didn't look very carefully!

**Comment by kensanata** [comment]
Haha, having to look very carefully is a sign that perhaps it should be easier to find!

**Comment by bjornbm** [comment]
Frankly the Contact link is quite visible at the top of your wiki so most likely I misremember and never really looked for contact details. Or maybe I did but couldn't be bothered with encrypting email and therefor opted for Github at the time, and subsequently forgetting about email being an option.
