### ISSUE TITLE
Confusion on Living World

### ISSUE THREAD

**Issue by jeremyf** [kensanata/halberdsnhelmets#4]
> Living World: Keep a list of a handful in addition to your list of contacts.

The above sentence is confusing. What handful should I be keeping

See https://github.com/kensanata/halberdsnhelmets/blob/0146056f95647ac97ae599e82f86af4454e2c353/Halberds%20and%20Helmets/Halberds-and-Helmets-Ref-Guide.ltx#L420

**Comment by kensanata** [comment]
Good point. I've rewritten that. Looks like a lot of copy & paste confusion. :)
